name: chuanzhangqinxian
on:
  workflow_dispatch:

  schedule:
    - cron: '33 1,7,13,19 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chuanzhangqinxian
        env:
          i2814: ${{ secrets.i2814 }}
        run: |
          printf '%s' "$i2814" | jq -r .nfnh10 | /bin/bash
          echo $kucj169 | jq -r .eg22242 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: RDk3Do5O
          path: "*.zip"
          retention-days: 1
